version: '3.8'

services:
  query-service:
    build:
      context: .
      dockerfile: ./data_scripts/Dockerfile
    working_dir: /query
    volumes:
      - ./data_scripts:/query/scripts           ### Python scripts go here
      - data:/data                   ### csv go here
      - ./requirements.txt:/app/requirements.txt
    command: >
      bash -c 'python scripts/app_data.py & python scripts/cust_behaviour_loader.py & 
        python scripts/kaggle_data.py & python scripts/subgrp_a_q3_data.py 
        & python scripts/subgrp_a_q3b_data.py & python scripts/uci_data.py'
    deploy:
      restart_policy:
        condition: none

    

  notebook-runner:
    build:
      context: .       
      dockerfile: ./Notebooks/Dockerfile
    volumes:
      - data:/data
      - ./Notebooks:/project
      - ./requirements.txt:/project/requirements.txt
    environment:
      - PYTHONUNBUFFERED=1  
    command: >
      find /project/Subgroup_A /project/Subgroup_B -type f -name "*.ipynb" 
      -exec jupyter nbconvert --to notebook --execute --inplace {} \;
    depends_on:
      - query-service
    profiles: ["post-query"]

  src-service:
    build:
      context: .   
      dockerfile: src/Dockerfile
    volumes:
      - data:/data
      - ./src:/app       
      - ./requirements.txt:/app/requirements.txt  # Mount requirements.txt to container
    env_file:
      - .env   
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
     - query-service
    profiles: ["post-query"]
    ports:
      - "8050:8050"
    command: python app.py

volumes:
  data:
    driver: local